name: MLflow CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Set up job
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      # Check environment
      - name: Check Env
        run: |
          python --version
          pip --version

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy xgboost matplotlib seaborn python-dotenv

      # Set MLflow Tracking URI and credentials
      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/covryzne/Eksperimen_SML_ShendiTeukuMaulanaEfendi.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=covryzne" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      # Run MLflow project
      - name: Run MLflow project
        run: |
          cd MLProject
          mlflow run . --no-conda -P data_path=student_habits_preprocessing.csv

      # Get latest MLflow run_id
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          run_id=$(mlflow runs list --experiment-id 0 | head -n 1 | awk '{print $2}')
          echo "::set-output name=run_id::$run_id"

      # Upload artifacts to GitHub LFS
      - name: Upload artifacts to GitHub LFS
        run: |
          git lfs install
          git lfs track "MLProject/mlruns/**/*"
          git add MLProject/mlruns/
          git add .gitattributes
          git commit -m "Add MLflow artifacts to LFS" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t workflow-ci:latest MLProject/

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag workflow-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci:latest

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci:latest

      # Post steps (cleanup)
      - name: Post Log in to Docker Hub
        if: always()
        run: |
          docker logout

      - name: Post Set up Python 3.12.7
        if: always()
        run: |
          echo "Python setup completed"

      - name: Post Run actions/checkout@v3
        if: always()
        run: |
          echo "Checkout completed"

      # Complete job
      - name: Complete job
        if: always()
        run: |
          echo "CI job completed"
