name: MLflow CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow==2.17.0 scikit-learn==1.5.2 pandas==2.2.3 numpy==2.1.2 xgboost==2.1.1 matplotlib==3.9.2 seaborn==0.13.2 python-dotenv==1.0.1

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/covryzne/Eksperimen_SML_ShendiTeukuMaulanaEfendi.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=covryzne" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run MLflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local -P data_path=student_habits_preprocessing.csv
          ls -la mlruns/ || echo "mlruns directory not found in MLProject after MLflow run"
          ls -la Membangun_model/ || echo "Membangun_model directory not found"

      - name: Get latest MLflow run_id
        run: |
          run_id=$(mlflow runs list --experiment-id 0 | head -n 1 | awk '{print $2}')
          echo "run_id=$run_id" >> $GITHUB_ENV

      - name: Upload artifacts to GitHub LFS
        run: |
          git lfs install
          git lfs track "MLProject/mlruns/**/*"
          ls -la MLProject/  # Debug: cek isi folder MLProject
          if [ -d "MLProject/mlruns" ]; then
            ls -la MLProject/mlruns/  # Debug: cek isi mlruns
            git add MLProject/mlruns/
            git add .gitattributes
            git commit -m "Add MLflow artifacts to LFS" || echo "No changes to commit"
            git push origin main
          else
            echo "No mlruns directory found, skipping LFS upload"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t workflow-ci:latest MLProject/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag workflow-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci:latest

      - name: Post Log in to Docker Hub
        if: always()
        run: |
          docker logout

      - name: Post Set up Python 3.12.7
        if: always()
        run: |
          echo "Python setup completed"

      - name: Post Run actions/checkout@v3
        if: always()
        run: |
          echo "Checkout completed"

      - name: Complete job
        if: always()
        run: |
          echo "CI job completed"
